### ISSUE TITLE
All CAPs

### ISSUE THREAD

**Issue by hsrai** [GreatDevelopers/WorkshopTraining#15]
Shops/Electric/Electric.md file have precautions written in All Capital (all characters are upper case), which is "shouting". Is it by chance, or it is done with some purpose.

**Comment by marvellouschandan** [comment]
Hope so it may be for clear visibility. Should we change it or leave as it?

**Comment by Sudhanshu-Dubey14** [comment]
It was like that in the original document which we converted. Maybe they made it so as to attract the attention of viewers. Should we change it?

**Comment by Sudhanshu-Dubey14** [comment]
@hsrai sir, I have made the required changes in Shops/Electric/Safety_Precautions.md in the new pull request. Please verify them.

**Comment by hsrai** [comment]
Case converted
